### ISSUE TITLE
fastecs is reporting different number of updates

### ISSUE THREAD

**Issue by ddmills** [ddmills/js-ecs-benchmarks#10]
fastecs is reporting a different number of updates (15000) on the Add/Remove suite. Expectation is that all libraries should have the same number here (25010000):

![image](https://user-images.githubusercontent.com/4615125/133895757-42932823-bd38-4144-b898-6068a821a617.png)

**Comment by ddmills** [comment]
introduced in #2 cc @octavetoast

**Comment by ddmills** [comment]
This number represents the number of times each individual entity was updated during the suite run

**Comment by octavetoast** [comment]
fastecs is no longer in development, I decided that there are no real good reasons to try to improve upon existing ecs implementations, they're pretty good already.

you can feel free to remove the fastecs bench, or if you want , i'll remove it and make a pr.
